#!/bin/bash

INPUTFILE=$1


#pixel
#Phi_healpix	Theta_healpix	Phi	Theta	R	Vphi	Vtheta	Vr	sig_Vphi	sig_Vtheta	sig_Vr	eVphi	eVtheta	eVr	sig_eVphi	sig_eVtheta	sig_eVr	Corr	sig_corr	Nobjects

plot_aitof_map $INPUTFILE ecl_pml_$INPUTFILE.png 1 2 6 0.2 0.6 "{/Symbol m}_le, mas/yr"
plot_aitof_map $INPUTFILE ecl_pmb_$INPUTFILE.png 1 2 7 0.2 0.6 "{/Symbol m}_be, mas/yr"
plot_aitof_map $INPUTFILE ecl_plx_$INPUTFILE.png 1 2 8 0.5 0.6 plx,mas

plot_aitof_map $INPUTFILE ecl_sigpml_$INPUTFILE.png 1 2 9 0.5 0.6 "{/Symbol s_{m}}_le,mas/yr"
plot_aitof_map $INPUTFILE ecl_sigpmb_$INPUTFILE.png 1 2 10 0.5 0.6 "{/Symbol s_{m}}_be,mas/yr"
plot_aitof_map $INPUTFILE ecl_sigplx_$INPUTFILE.png 1 2 11 0.8 0.6 "{/Symbol s}_{plx},mas"

plot_aitof_map $INPUTFILE ecl_pmra_$INPUTFILE.png 1 2 12 0.2 0.6 "{/Symbol m}_{{/Symbol a}}, mas/yr"
plot_aitof_map $INPUTFILE ecl_pmdec_$INPUTFILE.png 1 2 13 0.2 0.6 "{/Symbol m}_{{/Symbol d}}, mas/yr"

plot_aitof_map $INPUTFILE ecl_sig_pmra_$INPUTFILE.png 1 2 15 0.5 0.6 "{/Symbol s_{m}}_{/Symbol a},mas/yr"
plot_aitof_map $INPUTFILE ecl_sig_pmdec_$INPUTFILE.png 1 2 16 0.5 0.6 "{/Symbol s_{m}}_{/Symbol d},mas/yr"

plot_aitof_map $INPUTFILE ecl_pm_$INPUTFILE.png 1 2 21 0.3 0.6 "{/Symbol m},mas/yr"


plot_aitof_map $INPUTFILE gal_density_$INPUTFILE.png 1 2 20 5000 0.6 Density

