#!/bin/bash

INPUTFILE=$1
PSFILE=$2

xy1=$3
xy2=$4
xy3=$5
xy4=$6
name_x=$7
name_y=$8
name_legend1=$9
name_legend2=${10}
name_legend3=${11}
name_legend4=${12}
name_title=${13}
miny=${14}
maxy=${15}
#plot-1D res_1d_xyz_data_paola_sort_X.txt_R1.00_bin1_dx_0.1dy0.1dz0.1_cs.txt Vrot_R.eps '($3):(-$7)' '($3):(-$41)' '($3):(($30-$24)*$3-$50)' R Vrot avgVrot Vrot_{mod} Vrot_{OM+dVr/dth} avgTheta150to210degree
{
cat <<GnuplotScript
#cat <<EOF

#xmin=${minx}
#xmax=${maxx}

ymin=${miny}
ymax=${maxy}
#dx=${dx}
#dy=${dy}

set encoding utf8
set terminal pngcairo size 1400,1000 enhanced background rgb 'white' font "Symbola,24" 
set key noautotitle
set xlabel '${name_x}'
set ylabel '${name_y}'


set output '${PSFILE}'
#set xrange [xmin:xmax]
set yrange [ymin:ymax]
#set xtics dx
#set ytics dy
set grid x lw 2
set grid y lw 2

set title '${name_title}'

plot '${INPUTFILE}' using   $xy1 w l lc rgb "black" ,\
	'${INPUTFILE}' using   $xy2 w l lc rgb "red" ,\
	'${INPUTFILE}' using   $xy3 w l  lc rgb "blue" ,\
	'${INPUTFILE}' using   $xy4 w l lc rgb "green" ,\
	'${INPUTFILE}' using   $xy1 w err lc rgb "black" title '$name_legend1',\
        '${INPUTFILE}' using   $xy2 w err lc rgb "red" title '$name_legend2',\
        '${INPUTFILE}' using   $xy3 w err lc rgb "blue" title '$name_legend3',\
        '${INPUTFILE}' using   $xy4 w err lc rgb "green" title '$name_legend4'

GnuplotScript
} | gnuplot

#convert ${PSFILE} ${PSFILE}.png

#epstopdf  ${PSFILE}  --autorotate=All
#&& acroread $(basename ${PSFILE} .eps).pdf

