#!/bin/bash

INPUTFILE=$1
PSFILE=$2

x=$3
y=$4
z=$5
minx=$6
maxx=$7
miny=$8
maxy=$9
minz=${10}
maxz=${11}
name_x=${12}
name_y=${13}
name_z=${14}
xtic=${15}
ytic=${16}

{
cat <<GnuplotScript
#cat <<EOF

x=${x}
y=${y}
z=${z}

xmin=${minx}
xmax=${maxx}

ymin=${miny}
ymax=${maxy}

zmin=${minz}
zmax=${maxz}

xname=${name_x}
yname=${name_y}
zname=${name_z}

xtic=${xtic}
ytic=${ytic}

ondir = '${PSFILE}'
indata = '${INPUTFILE}'
indata_Sun = "Sun.dat"
indata_GC = "GalCenter.dat"

set encoding utf8
#set terminal gif animate delay 5 loop 0 optimize size 800,600
#set terminal pngcairo enhanced font "Symbola,16.0" size 540,420
set terminal epscairo color size 14,6 enhanced background rgb 'white' font "Symbola,36" solid

#set terminal epslatex standalone

#set terminal postscript enhanced
#set size 10.0,8

set key noautotitle
set angles degrees
set view map
set palette rgbformulae 33,13,10 #30,31,32 #33,13,10
set xtics xtic
set ytics ytic
set xrange [xmin:xmax]
set yrange [ymin:ymax]
set xlabel '${name_x}'
set ylabel '${name_y}'

set logscale zcb

π = 3.1415926535
R0 = 8.249

boxsize = 2
sunsize = 3
gcsize = 4

#set title '${name_z}'
set cbrange [zmin:zmax]
set cblabel '${name_z}'

set output '${PSFILE}'


	plot indata u x:y:z palette pt 5 ps boxsize, \
		indata_Sun u 1:2 ps sunsize pt 7 lc rgb "gold",\
                indata_GC u 1:2 ps gcsize pt 2 lc rgb "black"
GnuplotScript
} | gnuplot #&& ps2pdf Vrot.eps

convert ${PSFILE} ${PSFILE}.png 
#convert ${PSFILE} -rotate 90 ${PSFILE}.png

#epstopdf  ${PSFILE}  --autorotate=All
#&& acroread $(basename ${PSFILE} .eps).pdf

